version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: nativescript-barcodescanner
    versions:
    - 4.0.1
    - 4.1.0
  - dependency-name: tns-core-modules
    versions:
    - 3.4.1
    - 6.5.25
    - 6.5.26
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
    - 8.3.1
